server:
    port: 8080
spring:
    jmx:
      default-domain: EN
    # 静态文件请求匹配方式
    mvc: static-path-pattern=/**
    # 修改默认的静态寻址资源目录 多个使用逗号分隔
    resources: static-locations = classpath:/webapp/
    datasource:
      #使用druid连接池
      type: com.alibaba.druid.pool.DruidDataSource
      # 自定义的主数据源配置信息
    mail:
      host: smtp.gmail.com #host地址（可以在你的邮箱设置里找到）
      password: Primer3Plus  #密码
      fromuser: do_not_reply@hkgepitherapeutics.com #邮箱账号
      port: 587 #端口号
      default-encoding: UTF-8
      smtp:
        auth: true
        port: 587
        starttls: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
          port: 587
          fallback: false
primary:
    datasource:
      #druid相关配置
      druid:
        #监控统计拦截的filters
        filters: stat
        driverClassName: com.mysql.jdbc.Driver
        #配置基本属性
        url: jdbc:mysql://localhost:3306/epi?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
        username: root
        password: LZmy5cRxNcHQnxDhNtMm08t1dTncNuMkgU6+xZ3NPeY/Fu2LFGasDBEsFuel6A+osQljPgV5uMa3WqeZZpguaA==
        publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJlRkDJNrJVIJu/TMBFJwEJJOxu0V3fVvDa1FoMWNrO5JuadCub/wvjSDtGUB1RVPXUIN/KIxiarqi5eaeCTeiECAwEAAQ==
        #配置初始化大小/最小/最大
        initialSize: 1
        minIdle: 1
        maxActive: 20
        #获取连接等待超时时间
        maxWait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        timeBetweenEvictionRunsMillis: 60000
        #一个连接在池中最小生存的时间
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
    # 自定义的从数据源配置信息
back:
    datasource:
      #druid相关配置
      druid:
        #监控统计拦截的filters
        filters: stat
        driverClassName: com.mysql.jdbc.Driver
        #配置基本属性
        url: jdbc:mysql://localhost:3306/qtion?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
        username: root
        password: LZmy5cRxNcHQnxDhNtMm08t1dTncNuMkgU6+xZ3NPeY/Fu2LFGasDBEsFuel6A+osQljPgV5uMa3WqeZZpguaA==
        publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJlRkDJNrJVIJu/TMBFJwEJJOxu0V3fVvDa1FoMWNrO5JuadCub/wvjSDtGUB1RVPXUIN/KIxiarqi5eaeCTeiECAwEAAQ==
        #配置初始化大小/最小/最大
        initialSize: 1
        minIdle: 1
        maxActive: 20
        #获取连接等待超时时间
        maxWait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        timeBetweenEvictionRunsMillis: 60000
        #一个连接在池中最小生存的时间
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20


mybatis:
    configLocation: classpath:Mybatis/mybatis.xml              #mybatis配置文件路径
#    mapperLocations: classpath:mapper/*.xml  #所有mapper映射文件地址
#     # pojo类所在包路径
#    type-aliases-package: com.Bean
